version: "3.9"

services:
  envoy:
    image: envoyproxy/envoy:v1.28-latest
    container_name: envoy-gateway
    ports:
      - "443:443"
      - "9901:9901"
      - "59307:59307"
      - "59301:59301"
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
      - ./envoy/certs:/etc/envoy/certs:ro
    command:
      - -c
      - /etc/envoy/envoy.yaml
      - --log-level
      - info
    depends_on:
      - frontend
      - backend
      - backend-database
      - dazzleduck-ui
      - sql-controller
      - sql-controller2
    networks:
      - one211-network

  frontend:
    image: application-frontend:latest
    container_name: application-frontend
    depends_on:
      - backend
    ports:
      - "5173:5173"
    networks:
      - one211-network

  dazzleduck-ui:
    image: dazzleduck-frontend:latest
    container_name: dazzleduck-ui
    ports:
      - "5174:5174"
    networks:
      - one211-network

  backend:
    image: application-backend:latest
    container_name: application-backend
    depends_on:
      - backend-database
    environment:
      CORS_ALLOWED_ORIGINS: "https://frontend.one211.com:8443,http://localhost:5173,http://localhost:5174,https://frontend.one211.com,https://www.one211.com,https://dazzleduck-ui.com"
      SPRING_DATASOURCE_URL: jdbc:postgresql://backend-database:5432/one211
      SPRING_DATASOURCE_USERNAME: one211
      SPRING_DATASOURCE_PASSWORD: one211
      LOGGING_FORWARDING_ENABLED: "false"
      METRICS_FORWARDING_ENABLED: "false"
      JAVA_TOOL_OPTIONS: >
        --add-opens=java.base/java.nio=org.apache.arrow.memory.core,ALL-UNNAMED
    ports:
      - "8080:8080"
    networks:
      - one211-network

  backend-database:
    image: postgres:17.5
    container_name: application-database
    environment:
      POSTGRES_USER: one211
      POSTGRES_PASSWORD: one211
      POSTGRES_DB: one211
    ports:
      - "5433:5432"
    networks:
      - one211-network

  sql-controller:
    image: sql-controller:latest
    container_name: sql-controller
    depends_on:
      - backend
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dobservability.enabled=false
    command: >
      controller
      --conf flight_controller.flight.host=sql-controller
      --conf flight_controller.flight.port=59307
      --conf flight_controller.http.host=sql-controller
      --conf flight_controller.http.port=9006
      --conf 'flight_controller.login_url="http://backend:8080/api/login"'
      --conf flight_controller.access_mode=COMPLETE
      --conf 'flight_controller.allow-origin="https://dazzleduck-ui.com"'
    ports:
      - "9006:9006"
    volumes:
      - ./warehouse:/workspace/warehouse/httpfs_cache
    networks:
      - one211-network

  sql-controller2:
    image: sql-controller:latest
    container_name: sql-controller2
    depends_on:
      - backend
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dobservability.enabled=false
    command: >
      controller
      --conf flight_controller.flight.host=sql-controller2
      --conf flight_controller.flight.port=59301
      --conf flight_controller.http.host=sql-controller2
      --conf flight_controller.http.port=9007
      --conf 'flight_controller.login_url="http://backend:8080/api/login"'
      --conf flight_controller.access_mode=COMPLETE
      --conf 'flight_controller.allow-origin="https://dazzleduck-ui.com"'
    ports:
      - "9007:9007"
    volumes:
      - ./warehouse:/workspace/warehouse/httpfs_cache
    networks:
      - one211-network

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: http://minio:9000
    command: server /data --console-address ":9001"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - one211-network

  sql-executor:
    image: sql-controller:latest
    container_name: sql-executor
    depends_on:
      - sql-controller
      - sql-controller2
      - envoy
    environment:
      JAVA_TOOL_OPTIONS: >
        -Dobservability.enabled=false
    command: >
      executor
      --conf flight_executor.cluster=new_cluster
      --conf flight_executor.user=new_cluster
      --conf flight_executor.password=123456
      --conf flight_executor.secret_key=VGhpcyBpcyBhIDY0IGJpdCBsb25nIGtleSB3aGljaCBzaG91bGQgYmUgY2hhbmdlZCBpbiBwcm9kdWN0aW9uLiBTbyBjaGFuZ2UgbWUgYW5kIG1ha2Ugc3VyZSBpdHMgMTI4IGJpdCBsb25nIG9yIG1vcmU
      --conf flight_executor.controllers.0.host=envoy
      --conf flight_executor.controllers.0.port=59307
      --conf flight_executor.controllers.1.host=envoy
      --conf flight_executor.controllers.1.port=59301
      --conf 'dazzleduck_server.startup_script_provider.content="SELECT 1"'
    volumes:
      - ./warehouse:/workspace/warehouse/httpfs_cache
    networks:
      - one211-network
    restart: on-failure
    dns:
      - 8.8.8.8
      - 8.8.4.4

networks:
  one211-network:
    driver: bridge

volumes:
  minio_data:
